name: dockerize and deploy frontend webapp on ECS

on:
  release:

jobs:
  docker_build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::12353464364:role/gha-deploy-role
          aws-region: eu-central-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: build and push docker image to ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ecs-webapp-frontend
          IMAGE_TAG: ${{ github.ref_name }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

  deploy_to_ecs:
    needs: docker_build_and_push
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::12353464364:role/gha-deploy-role
          aws-region: eu-central-1  
        
      - name:  Render Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task_definition.json
          container-name: ecs-webapp-frontend
          image: ecr_registry/ecs-webapp-frontend:${{ github.ref_name }}
      
      - name: Trigger CodeDeploy deployment
        run: |
          aws ecs deploy \
          --service ecs-webapp-frontend-service \
          --task-definition ${{ steps.task-def.outputs.task-definition }} \
          --codedeploy-appspec file://appspec.yaml \
          --cluster ecs_webapp \
          --codedeploy-application ecs-webapp-codedeploy-app \
          --codedeploy-deployment-group ecs-webapp-codedeploy-frontend-group

